//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Output.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Output.Local.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Indentation Strategy.
        /// </summary>
        public static string STR_Cmd__ApplyTextIndentationStrategy {
            get {
                return ResourceManager.GetString("STR_Cmd__ApplyTextIndentationStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert text to lower case.
        /// </summary>
        public static string STR_Cmd__ConvertTextToLowerCase {
            get {
                return ResourceManager.GetString("STR_Cmd__ConvertTextToLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to Title Case.
        /// </summary>
        public static string STR_Cmd__ConvertTextToTitleCase {
            get {
                return ResourceManager.GetString("STR_Cmd__ConvertTextToTitleCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert Case.
        /// </summary>
        public static string STR_Cmd__InvertTextCase {
            get {
                return ResourceManager.GetString("STR_Cmd__InvertTextCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract Class.
        /// </summary>
        public static string STR_CMD_AbstractClass {
            get {
                return ResourceManager.GetString("STR_CMD_AbstractClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Abstract Class shape.
        /// </summary>
        public static string STR_CMD_AbstractClass_DESCRIPTION {
            get {
                return ResourceManager.GetString("STR_CMD_AbstractClass_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregation.
        /// </summary>
        public static string STR_CMD_Aggregation {
            get {
                return ResourceManager.GetString("STR_CMD_Aggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new aggregation.
        /// </summary>
        public static string STR_CMD_Aggregation_description {
            get {
                return ResourceManager.GetString("STR_CMD_Aggregation_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association.
        /// </summary>
        public static string STR_CMD_Association {
            get {
                return ResourceManager.GetString("STR_CMD_Association", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new association.
        /// </summary>
        public static string STR_CMD_Association_description {
            get {
                return ResourceManager.GetString("STR_CMD_Association_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Theme.
        /// </summary>
        public static string STR_CMD_CHANGETheme {
            get {
                return ResourceManager.GetString("STR_CMD_CHANGETheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the color theme of the application..
        /// </summary>
        public static string STR_CMD_ChangeTheme_DESCRIPTION {
            get {
                return ResourceManager.GetString("STR_CMD_ChangeTheme_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string STR_CMD_Class {
            get {
                return ResourceManager.GetString("STR_CMD_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Class shape.
        /// </summary>
        public static string STR_CMD_Class_description {
            get {
                return ResourceManager.GetString("STR_CMD_Class_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse text foldings.
        /// </summary>
        public static string STR_Cmd_CollapseTextFoldings {
            get {
                return ResourceManager.GetString("STR_Cmd_CollapseTextFoldings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string STR_CMD_Comment {
            get {
                return ResourceManager.GetString("STR_CMD_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Comment shape.
        /// </summary>
        public static string STR_CMD_Comment_description {
            get {
                return ResourceManager.GetString("STR_CMD_Comment_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composition.
        /// </summary>
        public static string STR_CMD_Composition {
            get {
                return ResourceManager.GetString("STR_CMD_Composition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new composition.
        /// </summary>
        public static string STR_CMD_Composition_description {
            get {
                return ResourceManager.GetString("STR_CMD_Composition_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert Leading Spaces to Tabs.
        /// </summary>
        public static string STR_Cmd_ConvertLeadingSpaces {
            get {
                return ResourceManager.GetString("STR_Cmd_ConvertLeadingSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert Leading Tabs to Spaces.
        /// </summary>
        public static string STR_Cmd_ConvertLeadingTabsToSpaces {
            get {
                return ResourceManager.GetString("STR_Cmd_ConvertLeadingTabsToSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert Spaces to Tabs.
        /// </summary>
        public static string STR_CMD_ConvertSpacesToTabs {
            get {
                return ResourceManager.GetString("STR_CMD_ConvertSpacesToTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert Tabs to Spaces.
        /// </summary>
        public static string STR_CMD_ConvertTabsToSpaces {
            get {
                return ResourceManager.GetString("STR_CMD_ConvertTabsToSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert text to upper case.
        /// </summary>
        public static string STR_Cmd_ConvertTextToUpperCase {
            get {
                return ResourceManager.GetString("STR_Cmd_ConvertTextToUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string STR_CMD_CreateNew {
            get {
                return ResourceManager.GetString("STR_CMD_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new document..
        /// </summary>
        public static string STR_CMD_CreateNewDocument {
            get {
                return ResourceManager.GetString("STR_CMD_CreateNewDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegate.
        /// </summary>
        public static string STR_CMD_Delegate {
            get {
                return ResourceManager.GetString("STR_CMD_Delegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new delegate element.
        /// </summary>
        public static string STR_CMD_Delegate_description {
            get {
                return ResourceManager.GetString("STR_CMD_Delegate_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string STR_CMD_Delete {
            get {
                return ResourceManager.GetString("STR_CMD_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the selected shapes..
        /// </summary>
        public static string STR_CMD_Delete_description {
            get {
                return ResourceManager.GetString("STR_CMD_Delete_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment.
        /// </summary>
        public static string STR_CMD_Deployment {
            get {
                return ResourceManager.GetString("STR_CMD_Deployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new deployment element.
        /// </summary>
        public static string STR_CMD_Deployment_description {
            get {
                return ResourceManager.GetString("STR_CMD_Deployment_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum.
        /// </summary>
        public static string STR_CMD_Enum {
            get {
                return ResourceManager.GetString("STR_CMD_Enum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Enum shape.
        /// </summary>
        public static string STR_CMD_Enum_description {
            get {
                return ResourceManager.GetString("STR_CMD_Enum_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand text foldings.
        /// </summary>
        public static string STR_Cmd_ExpandTextFoldings {
            get {
                return ResourceManager.GetString("STR_Cmd_ExpandTextFoldings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string STR_CMD_Export_Command {
            get {
                return ResourceManager.GetString("STR_CMD_Export_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the current document as image bitmap..
        /// </summary>
        public static string STR_CMD_Export_Command_DESCR {
            get {
                return ResourceManager.GetString("STR_CMD_Export_Command_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inheritance association.
        /// </summary>
        public static string STR_CMD_InheritanceAssociation {
            get {
                return ResourceManager.GetString("STR_CMD_InheritanceAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new inheritance association.
        /// </summary>
        public static string STR_CMD_InheritanceAssociation_description {
            get {
                return ResourceManager.GetString("STR_CMD_InheritanceAssociation_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface.
        /// </summary>
        public static string STR_CMD_Interface {
            get {
                return ResourceManager.GetString("STR_CMD_Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Interface shape.
        /// </summary>
        public static string STR_CMD_Interface_description {
            get {
                return ResourceManager.GetString("STR_CMD_Interface_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open an existing document..
        /// </summary>
        public static string STR_CMD_OpenDocument {
            get {
                return ResourceManager.GetString("STR_CMD_OpenDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print the current document..
        /// </summary>
        public static string STR_CMD_PRINT_DESCRIPTION {
            get {
                return ResourceManager.GetString("STR_CMD_PRINT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo last undo.
        /// </summary>
        public static string STR_CMD_REDO_DESCRIPTION {
            get {
                return ResourceManager.GetString("STR_CMD_REDO_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Leading White Spaces.
        /// </summary>
        public static string STR_CMD_RemoveLeadingWhiteSpace {
            get {
                return ResourceManager.GetString("STR_CMD_RemoveLeadingWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Trailing White Space.
        /// </summary>
        public static string STR_CMD_RemoveTrailingWhiteSpace {
            get {
                return ResourceManager.GetString("STR_CMD_RemoveTrailingWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the current document..
        /// </summary>
        public static string STR_CMD_SAVE_DOCUMENT {
            get {
                return ResourceManager.GetString("STR_CMD_SAVE_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the current document to a new file.
        /// </summary>
        public static string STR_CMD_SAVEAS_DOCUMENT {
            get {
                return ResourceManager.GetString("STR_CMD_SAVEAS_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Struct.
        /// </summary>
        public static string STR_CMD_Struct {
            get {
                return ResourceManager.GetString("STR_CMD_Struct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Struct shape.
        /// </summary>
        public static string STR_CMD_Struct_description {
            get {
                return ResourceManager.GetString("STR_CMD_Struct_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo last edit.
        /// </summary>
        public static string STR_CMD_UNDO_DESCRIPTION {
            get {
                return ResourceManager.GetString("STR_CMD_UNDO_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Designer.
        /// </summary>
        public static string STR_CMD_UPDATE {
            get {
                return ResourceManager.GetString("STR_CMD_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update the design surface to reflect changes made to the underlying XML document..
        /// </summary>
        public static string STR_CMD_UPDATE_DESCRIPTION {
            get {
                return ResourceManager.GetString("STR_CMD_UPDATE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string STR_CmdName_Copy {
            get {
                return ResourceManager.GetString("STR_CmdName_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selected item.
        /// </summary>
        public static string STR_CmdName_Copy_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Copy_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string STR_CmdName_Cut {
            get {
                return ResourceManager.GetString("STR_CmdName_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut selected item.
        /// </summary>
        public static string STR_CmdName_Cut_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Cut_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string STR_CmdName_Delete {
            get {
                return ResourceManager.GetString("STR_CmdName_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected item.
        /// </summary>
        public static string STR_CmdName_Delete_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Delete_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Line.
        /// </summary>
        public static string STR_CmdName_DeleteLine {
            get {
                return ResourceManager.GetString("STR_CmdName_DeleteLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes the current line of text.
        /// </summary>
        public static string STR_CmdName_DeleteLine_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_DeleteLine_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string STR_CmdName_Paste {
            get {
                return ResourceManager.GetString("STR_CmdName_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste item from Windows clipboard.
        /// </summary>
        public static string STR_CmdName_Paste_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Paste_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string STR_CmdName_Redo {
            get {
                return ResourceManager.GetString("STR_CmdName_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo last undo.
        /// </summary>
        public static string STR_CmdName_Redo_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Redo_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string STR_CmdName_SelectAll {
            get {
                return ResourceManager.GetString("STR_CmdName_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all items.
        /// </summary>
        public static string STR_CmdName_SelectAll_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_SelectAll_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string STR_CmdName_Undo {
            get {
                return ResourceManager.GetString("STR_CmdName_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo last edit.
        /// </summary>
        public static string STR_CmdName_Undo_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Undo_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the selected shapes to the clipboard..
        /// </summary>
        public static string STR_COPY_Description {
            get {
                return ResourceManager.GetString("STR_COPY_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut the selected shapes to the clipboard..
        /// </summary>
        public static string STR_CUT_Description {
            get {
                return ResourceManager.GetString("STR_CUT_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        public static string STR_Default_FileName {
            get {
                return ResourceManager.GetString("STR_Default_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Files (*.xml)|*.xml|All files (*.*)|*.*.
        /// </summary>
        public static string STR_FILETYPE_FILTER {
            get {
                return ResourceManager.GetString("STR_FILETYPE_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG Image Files (*.png)|*.png|
        ///JPEG Image Files (*.jpg;*.jpeg)|*.jpg;*.jpeg|
        ///Windows Bitmap Image Files (*.bmp)|*.bmp|
        ///XPS Document Files (*.xps)|*.xps.
        /// </summary>
        public static string STR_FILETYPE_FILTER_EXPORT {
            get {
                return ResourceManager.GetString("STR_FILETYPE_FILTER_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Files (MiniUML.Themes.*.dll)|MiniUML.Themes.*.dll.
        /// </summary>
        public static string STR_FILETYPE_FILTER_PLUGINS {
            get {
                return ResourceManager.GetString("STR_FILETYPE_FILTER_PLUGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Files (*.xml)|*.xml.
        /// </summary>
        public static string STR_FILETYPE_FILTER_SAVE {
            get {
                return ResourceManager.GetString("STR_FILETYPE_FILTER_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Case.
        /// </summary>
        public static string STR_Label_TextCase {
            get {
                return ResourceManager.GetString("STR_Label_TextCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White Spaces.
        /// </summary>
        public static string STR_Label_WhiteSpaces {
            get {
                return ResourceManager.GetString("STR_Label_WhiteSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add _Class.
        /// </summary>
        public static string STR_MENUITEM_ADD_CLASS {
            get {
                return ResourceManager.GetString("STR_MENUITEM_ADD_CLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add _Member.
        /// </summary>
        public static string STR_MENUITEM_ADD_ENUM_MEMBER {
            get {
                return ResourceManager.GetString("STR_MENUITEM_ADD_ENUM_MEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add _Event.
        /// </summary>
        public static string STR_MENUITEM_ADD_EVENT {
            get {
                return ResourceManager.GetString("STR_MENUITEM_ADD_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add _Field.
        /// </summary>
        public static string STR_MENUITEM_ADD_FIELD {
            get {
                return ResourceManager.GetString("STR_MENUITEM_ADD_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add _Method.
        /// </summary>
        public static string STR_MENUITEM_ADD_METHOD {
            get {
                return ResourceManager.GetString("STR_MENUITEM_ADD_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add _Property.
        /// </summary>
        public static string STR_MENUITEM_ADD_PROPERTY {
            get {
                return ResourceManager.GetString("STR_MENUITEM_ADD_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring to Front.
        /// </summary>
        public static string STR_MENUITEM_BringToFront {
            get {
                return ResourceManager.GetString("STR_MENUITEM_BringToFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string STR_MENUITEM_DELETE {
            get {
                return ResourceManager.GetString("STR_MENUITEM_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to Back.
        /// </summary>
        public static string STR_MENUITEM_SendToBack {
            get {
                return ResourceManager.GetString("STR_MENUITEM_SendToBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid resolution..
        /// </summary>
        public static string STR_MSG_INVALID_RESOLUTION {
            get {
                return ResourceManager.GetString("STR_MSG_INVALID_RESOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The clipboard does not contain any shapes!.
        /// </summary>
        public static string STR_MSG_NoShapeInClipboard {
            get {
                return ResourceManager.GetString("STR_MSG_NoShapeInClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more page definition fields are not valid..
        /// </summary>
        public static string STR_MSG_PAGE_DEFINITION_FIELD_INVALID {
            get {
                return ResourceManager.GetString("STR_MSG_PAGE_DEFINITION_FIELD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page dimensions (Height: {0}, Width: {1}) cannot be negative..
        /// </summary>
        public static string STR_MSG_PAGE_HEIGHT_WIDTH_NEGATIVE {
            get {
                return ResourceManager.GetString("STR_MSG_PAGE_HEIGHT_WIDTH_NEGATIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page margins are larger than page size..
        /// </summary>
        public static string STR_MSG_PAGE_MARGIN_LARGER_THAN_PAGESIZE {
            get {
                return ResourceManager.GetString("STR_MSG_PAGE_MARGIN_LARGER_THAN_PAGESIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page margins cannot be negative..
        /// </summary>
        public static string STR_MSG_PAGE_MARGINS_NEGATIVE {
            get {
                return ResourceManager.GetString("STR_MSG_PAGE_MARGINS_NEGATIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string STR_MSG_Warning_Caption {
            get {
                return ResourceManager.GetString("STR_MSG_Warning_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while opening the file &apos;{0}&apos;..
        /// </summary>
        public static string STR_OpenFILE_MSG {
            get {
                return ResourceManager.GetString("STR_OpenFILE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation aborted.
        /// </summary>
        public static string STR_OpenFILE_MSG_CAPTION {
            get {
                return ResourceManager.GetString("STR_OpenFILE_MSG_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste the contents of the clipboard into the document..
        /// </summary>
        public static string STR_PASTE_Description {
            get {
                return ResourceManager.GetString("STR_PASTE_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes to {0}?.
        /// </summary>
        public static string STR_QUERY_SAVE_CHANGES {
            get {
                return ResourceManager.GetString("STR_QUERY_SAVE_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes?.
        /// </summary>
        public static string STR_QUERY_SAVE_CHANGES_CAPTION {
            get {
                return ResourceManager.GetString("STR_QUERY_SAVE_CHANGES_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while saving the file &apos;{0}&apos;..
        /// </summary>
        public static string STR_SaveFILE_MSG {
            get {
                return ResourceManager.GetString("STR_SaveFILE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation aborted..
        /// </summary>
        public static string STR_SaveFILE_MSG_CAPTION {
            get {
                return ResourceManager.GetString("STR_SaveFILE_MSG_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string STR_Select {
            get {
                return ResourceManager.GetString("STR_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to select mode..
        /// </summary>
        public static string STR_Select_Description {
            get {
                return ResourceManager.GetString("STR_Select_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Editor.
        /// </summary>
        public static string STR_TITLE_XML_Editor {
            get {
                return ResourceManager.GetString("STR_TITLE_XML_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UML Class Diagram.
        /// </summary>
        public static string STR_UML_CLASS_DIAGRAM_TT {
            get {
                return ResourceManager.GetString("STR_UML_CLASS_DIAGRAM_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error.
        /// </summary>
        public static string STR_UnexpectedErrorCaption {
            get {
                return ResourceManager.GetString("STR_UnexpectedErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string STR_ZOOMSlider_PercentCharacter {
            get {
                return ResourceManager.GetString("STR_ZOOMSlider_PercentCharacter", resourceCulture);
            }
        }
    }
}
