//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileSystemModels.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileSystemModels.Local.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy path into Windows Clipboard....
        /// </summary>
        public static string CMD_Copy_Path_To_Clipboard_Label {
            get {
                return ResourceManager.GetString("CMD_Copy_Path_To_Clipboard_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy as path into Windows clipboard..
        /// </summary>
        public static string CMD_Copy_Path_To_Clipboard_Label_TT {
            get {
                return ResourceManager.GetString("CMD_Copy_Path_To_Clipboard_Label_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy as path into Windows clipboard..
        /// </summary>
        public static string CMD_Copy_Path_To_Clipboard_Label_TT1 {
            get {
                return ResourceManager.GetString("CMD_Copy_Path_To_Clipboard_Label_TT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy path into Windows Clipboard....
        /// </summary>
        public static string CMD_Copy_Path_To_Clipboard_Label1 {
            get {
                return ResourceManager.GetString("CMD_Copy_Path_To_Clipboard_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open ....
        /// </summary>
        public static string CMD_Open_in_Application_Label {
            get {
                return ResourceManager.GetString("CMD_Open_in_Application_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the selected file in the application..
        /// </summary>
        public static string CMD_Open_in_Application_Label_TT {
            get {
                return ResourceManager.GetString("CMD_Open_in_Application_Label_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder in Windows Explorer....
        /// </summary>
        public static string CMD_Open_in_Windows_Label {
            get {
                return ResourceManager.GetString("CMD_Open_in_Windows_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the Windows Explorer with the selected folder..
        /// </summary>
        public static string CMD_Open_in_Windows_Label_TT {
            get {
                return ResourceManager.GetString("CMD_Open_in_Windows_Label_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the Windows Explorer with the selected folder..
        /// </summary>
        public static string CMD_Open_in_Windows_Label_TT1 {
            get {
                return ResourceManager.GetString("CMD_Open_in_Windows_Label_TT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder in Windows Explorer....
        /// </summary>
        public static string CMD_Open_in_Windows_Label1 {
            get {
                return ResourceManager.GetString("CMD_Open_in_Windows_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Windows....
        /// </summary>
        public static string CMD_Open_with_Windows_Association_Label {
            get {
                return ResourceManager.GetString("CMD_Open_with_Windows_Association_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute the selected item (folder or file) with default Windows application..
        /// </summary>
        public static string CMD_Open_with_Windows_Association_Label_TT {
            get {
                return ResourceManager.GetString("CMD_Open_with_Windows_Association_Label_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark folder.
        /// </summary>
        public static string CMD_RecentFolderAdd_Label {
            get {
                return ResourceManager.GetString("CMD_RecentFolderAdd_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark folder.
        /// </summary>
        public static string CMD_RecentFolderAdd_Label1 {
            get {
                return ResourceManager.GetString("CMD_RecentFolderAdd_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds the selected folder to the list of bookmarked folders..
        /// </summary>
        public static string CMD_RecentFolderAdd_TT {
            get {
                return ResourceManager.GetString("CMD_RecentFolderAdd_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds the selected folder to the list of bookmarked folders..
        /// </summary>
        public static string CMD_RecentFolderAdd_TT1 {
            get {
                return ResourceManager.GetString("CMD_RecentFolderAdd_TT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove folder bookmark.
        /// </summary>
        public static string CMD_RecentFolderRemove_Label {
            get {
                return ResourceManager.GetString("CMD_RecentFolderRemove_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove folder bookmark.
        /// </summary>
        public static string CMD_RecentFolderRemove_Label1 {
            get {
                return ResourceManager.GetString("CMD_RecentFolderRemove_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the selected folder from the list of bookmarked folders..
        /// </summary>
        public static string CMD_RecentFolderRemove_TT {
            get {
                return ResourceManager.GetString("CMD_RecentFolderRemove_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the selected folder from the list of bookmarked folders..
        /// </summary>
        public static string CMD_RecentFolderRemove_TT1 {
            get {
                return ResourceManager.GetString("CMD_RecentFolderRemove_TT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder....
        /// </summary>
        public static string CMD_Select_Folder_Label {
            get {
                return ResourceManager.GetString("CMD_Select_Folder_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects the current folder and updates all related views..
        /// </summary>
        public static string CMD_Select_Folder_Label_TT {
            get {
                return ResourceManager.GetString("CMD_Select_Folder_Label_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show or hide folder..
        /// </summary>
        public static string CMD_ToggleIsFolderVisibleCommand_TT {
            get {
                return ResourceManager.GetString("CMD_ToggleIsFolderVisibleCommand_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show or hide icons..
        /// </summary>
        public static string CMD_ToggleIsIconVisibleCommand_TT {
            get {
                return ResourceManager.GetString("CMD_ToggleIsIconVisibleCommand_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        public static string FolderItem_Desktop {
            get {
                return ResourceManager.GetString("FolderItem_Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Documents.
        /// </summary>
        public static string FolderItem_MyDocuments {
            get {
                return ResourceManager.GetString("FolderItem_MyDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \/:*?&quot;&lt;&gt;|.
        /// </summary>
        public static string ForbiddenRenameKeys {
            get {
                return ResourceManager.GetString("ForbiddenRenameKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A name cannot contain any of the following characters:
        ///\/:*?&quot;&lt;&gt;|.
        /// </summary>
        public static string ForbiddenRenameKeysMessage {
            get {
                return ResourceManager.GetString("ForbiddenRenameKeysMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Character Input.
        /// </summary>
        public static string ForbiddenRenameKeysTitle {
            get {
                return ResourceManager.GetString("ForbiddenRenameKeysTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back one location..
        /// </summary>
        public static string NavigateBackCommand_TT {
            get {
                return ResourceManager.GetString("NavigateBackCommand_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go forward one location..
        /// </summary>
        public static string NavigateForwardCommand_TT {
            get {
                return ResourceManager.GetString("NavigateForwardCommand_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate up to parent.
        /// </summary>
        public static string NavigateUpCommand_TT {
            get {
                return ResourceManager.GetString("NavigateUpCommand_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update listed items..
        /// </summary>
        public static string RefreshCommand_TT {
            get {
                return ResourceManager.GetString("RefreshCommand_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a filter to restrict the listed files..
        /// </summary>
        public static string SelectFilterCommand_TT {
            get {
                return ResourceManager.GetString("SelectFilterCommand_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a location to navigate to it..
        /// </summary>
        public static string SelectLocationCommand_TT {
            get {
                return ResourceManager.GetString("SelectLocationCommand_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while creating new folder.
        /// </summary>
        public static string STR_CREATE_FOLDER_ERROR_TITLE {
            get {
                return ResourceManager.GetString("STR_CREATE_FOLDER_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device is not ready..
        /// </summary>
        public static string STR_MSG_DEVICE_NOT_READY {
            get {
                return ResourceManager.GetString("STR_MSG_DEVICE_NOT_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device is not ready..
        /// </summary>
        public static string STR_MSG_DEVICE_NOT_READY1 {
            get {
                return ResourceManager.GetString("STR_MSG_DEVICE_NOT_READY1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory &apos;{0}&apos; does not exist or cannot be accessed..
        /// </summary>
        public static string STR_MSG_DIRECTORY_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("STR_MSG_DIRECTORY_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory &apos;{0}&apos; does not exist or cannot be accessed..
        /// </summary>
        public static string STR_MSG_DIRECTORY_DOES_NOT_EXIST1 {
            get {
                return ResourceManager.GetString("STR_MSG_DIRECTORY_DOES_NOT_EXIST1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error finding requested resource..
        /// </summary>
        public static string STR_MSG_ERROR_FINDING_RESOURCE {
            get {
                return ResourceManager.GetString("STR_MSG_ERROR_FINDING_RESOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error finding requested resource..
        /// </summary>
        public static string STR_MSG_ERROR_FINDING_RESOURCE1 {
            get {
                return ResourceManager.GetString("STR_MSG_ERROR_FINDING_RESOURCE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error.
        /// </summary>
        public static string STR_MSG_InvalidChar_TITLE {
            get {
                return ResourceManager.GetString("STR_MSG_InvalidChar_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured..
        /// </summary>
        public static string STR_MSG_UnknownError {
            get {
                return ResourceManager.GetString("STR_MSG_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New folder.
        /// </summary>
        public static string STR_NEW_DEFAULT_FOLDER_NAME {
            get {
                return ResourceManager.GetString("STR_NEW_DEFAULT_FOLDER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        public static string STR_NewFolder_Command {
            get {
                return ResourceManager.GetString("STR_NewFolder_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new folder in the Windows file system.
        /// </summary>
        public static string STR_NewFolder_Command_TT {
            get {
                return ResourceManager.GetString("STR_NewFolder_Command_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string STR_Rename_Command {
            get {
                return ResourceManager.GetString("STR_Rename_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename an item in the Windows file system.
        /// </summary>
        public static string STR_Rename_Command_TT {
            get {
                return ResourceManager.GetString("STR_Rename_Command_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while renaming folder.
        /// </summary>
        public static string STR_RenameFolderErrorTitle {
            get {
                return ResourceManager.GetString("STR_RenameFolderErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply or remove the currently configured filter.
        /// </summary>
        public static string ToggleIsFilteredCommand_TT {
            get {
                return ResourceManager.GetString("ToggleIsFilteredCommand_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show or hide hidden files and folders..
        /// </summary>
        public static string ToggleIsHiddenVisibleCommand_TT {
            get {
                return ResourceManager.GetString("ToggleIsHiddenVisibleCommand_TT", resourceCulture);
            }
        }
    }
}
