//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edi.Util.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Edi.Util.Local.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show information about EDI.
        /// </summary>
        public static string CMD_APP_About_Description {
            get {
                return ResourceManager.GetString("CMD_APP_About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close document.
        /// </summary>
        public static string CMD_APP_CloseDoc_Description {
            get {
                return ResourceManager.GetString("CMD_APP_CloseDoc_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit application.
        /// </summary>
        public static string CMD_App_Exit_Describtion {
            get {
                return ResourceManager.GetString("CMD_App_Exit_Describtion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to HTML.
        /// </summary>
        public static string CMD_APP_ExportTextToHTML_Description {
            get {
                return ResourceManager.GetString("CMD_APP_ExportTextToHTML_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UML to Image.
        /// </summary>
        public static string CMD_APP_ExportUMLToImage_Description {
            get {
                return ResourceManager.GetString("CMD_APP_ExportUMLToImage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file ....
        /// </summary>
        public static string CMD_APP_Open_Description {
            get {
                return ResourceManager.GetString("CMD_APP_Open_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open URL ....
        /// </summary>
        public static string CMD_APP_OpenURL_Description {
            get {
                return ResourceManager.GetString("CMD_APP_OpenURL_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All ....
        /// </summary>
        public static string CMD_APP_SaveAll_Description {
            get {
                return ResourceManager.GetString("CMD_APP_SaveAll_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Start Page.
        /// </summary>
        public static string CMD_APP_ShowStartPage_Description {
            get {
                return ResourceManager.GetString("CMD_APP_ShowStartPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle display of optional elements like statusbar and toolbar..
        /// </summary>
        public static string CMD_APP_ToggleOptimizeWorkspace_Description {
            get {
                return ResourceManager.GetString("CMD_APP_ToggleOptimizeWorkspace_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change theme.
        /// </summary>
        public static string CMD_APP_ViewTheme_Description {
            get {
                return ResourceManager.GetString("CMD_APP_ViewTheme_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add MRU Entry.
        /// </summary>
        public static string CMD_MRU_AddEntry_Description {
            get {
                return ResourceManager.GetString("CMD_MRU_AddEntry_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin or unpin an MRU entry.
        /// </summary>
        public static string CMD_MRU_Pin_Description {
            get {
                return ResourceManager.GetString("CMD_MRU_Pin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove MRU Entry.
        /// </summary>
        public static string CMD_MRU_RemoveEntry_Description {
            get {
                return ResourceManager.GetString("CMD_MRU_RemoveEntry_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch off syntax highlighting for current file.
        /// </summary>
        public static string CMD_TXT_DisableHighlighting_Description {
            get {
                return ResourceManager.GetString("CMD_TXT_DisableHighlighting_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find specific text in a document.
        /// </summary>
        public static string CMD_TXT_FindNext_Description {
            get {
                return ResourceManager.GetString("CMD_TXT_FindNext_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find next occurrence of specific text in a document.
        /// </summary>
        public static string CMD_TXT_FindNextText_Description {
            get {
                return ResourceManager.GetString("CMD_TXT_FindNextText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find previous occurrence of specific text in a document.
        /// </summary>
        public static string CMD_TXT_FindPreviousText_Description {
            get {
                return ResourceManager.GetString("CMD_TXT_FindPreviousText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and replace a specific text in a document.
        /// </summary>
        public static string CMD_TXT_FindReplaceText_Description {
            get {
                return ResourceManager.GetString("CMD_TXT_FindReplaceText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to a specific line in a document.
        /// </summary>
        public static string CMD_TXT_GotoLine_Description {
            get {
                return ResourceManager.GetString("CMD_TXT_GotoLine_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Completion:.
        /// </summary>
        public static string STR_ABOUT_CODE_COMPLETION {
            get {
                return ResourceManager.GetString("STR_ABOUT_CODE_COMPLETION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docking Layout System:.
        /// </summary>
        public static string STR_ABOUT_DOCKING_LAYOUT {
            get {
                return ResourceManager.GetString("STR_ABOUT_DOCKING_LAYOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log4Net Viewer:.
        /// </summary>
        public static string STR_ABOUT_Log4NetViewer {
            get {
                return ResourceManager.GetString("STR_ABOUT_Log4NetViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Text and UML Editor..
        /// </summary>
        public static string STR_ABOUT_MSG {
            get {
                return ResourceManager.GetString("STR_ABOUT_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _OK.
        /// </summary>
        public static string STR_ABOUT_OK_BUTTON {
            get {
                return ResourceManager.GetString("STR_ABOUT_OK_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Editor:.
        /// </summary>
        public static string STR_ABOUT_TextEditor {
            get {
                return ResourceManager.GetString("STR_ABOUT_TextEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string STR_ABOUT_Version {
            get {
                return ResourceManager.GetString("STR_ABOUT_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Info.
        /// </summary>
        public static string STR_ABOUT_VERSION_INFO_LABEL {
            get {
                return ResourceManager.GetString("STR_ABOUT_VERSION_INFO_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory &apos;{0}&apos; does not exist or cannot be accessed..
        /// </summary>
        public static string STR_ACCESS_DIRECTORY_ERROR {
            get {
                return ResourceManager.GetString("STR_ACCESS_DIRECTORY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy path to clipboard.
        /// </summary>
        public static string STR_AppCommand_CopyFileURLToClipboard {
            get {
                return ResourceManager.GetString("STR_AppCommand_CopyFileURLToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the path of this document into the Windows Clipboard.
        /// </summary>
        public static string STR_AppCommand_CopyFileURLToClipboard_TT {
            get {
                return ResourceManager.GetString("STR_AppCommand_CopyFileURLToClipboard_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Containing folder....
        /// </summary>
        public static string STR_AppCommand_OpenContainingFolder {
            get {
                return ResourceManager.GetString("STR_AppCommand_OpenContainingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the folder that contains this document in Windows Explorer.
        /// </summary>
        public static string STR_AppCommand_OpenContainingFolder_TT {
            get {
                return ResourceManager.GetString("STR_AppCommand_OpenContainingFolder_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set path in Explorer tool window.
        /// </summary>
        public static string STR_AppCommand_SyncPathToExplorerCommand {
            get {
                return ResourceManager.GetString("STR_AppCommand_SyncPathToExplorerCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display document in Explorer tool window.
        /// </summary>
        public static string STR_AppCommand_SyncPathToExplorerCommand_TT {
            get {
                return ResourceManager.GetString("STR_AppCommand_SyncPathToExplorerCommand_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string STR_Category_Error {
            get {
                return ResourceManager.GetString("STR_Category_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string STR_Category_Information {
            get {
                return ResourceManager.GetString("STR_Category_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Error.
        /// </summary>
        public static string STR_Category_InternalError {
            get {
                return ResourceManager.GetString("STR_Category_InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Internal Error.
        /// </summary>
        public static string STR_Category_Unknown_Internal_Error {
            get {
                return ResourceManager.GetString("STR_Category_Unknown_Internal_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        public static string STR_Category_UnknownError {
            get {
                return ResourceManager.GetString("STR_Category_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string STR_Category_Warning {
            get {
                return ResourceManager.GetString("STR_Category_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Indentation Strategy.
        /// </summary>
        public static string STR_Cmd__ApplyTextIndentationStrategy {
            get {
                return ResourceManager.GetString("STR_Cmd__ApplyTextIndentationStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert text to lower case.
        /// </summary>
        public static string STR_Cmd__ConvertTextToLowerCase {
            get {
                return ResourceManager.GetString("STR_Cmd__ConvertTextToLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to Title Case.
        /// </summary>
        public static string STR_Cmd__ConvertTextToTitleCase {
            get {
                return ResourceManager.GetString("STR_Cmd__ConvertTextToTitleCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert Case.
        /// </summary>
        public static string STR_Cmd__InvertTextCase {
            get {
                return ResourceManager.GetString("STR_Cmd__InvertTextCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse text foldings.
        /// </summary>
        public static string STR_Cmd_CollapseTextFoldings {
            get {
                return ResourceManager.GetString("STR_Cmd_CollapseTextFoldings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert Leading Spaces to Tabs.
        /// </summary>
        public static string STR_Cmd_ConvertLeadingSpaces {
            get {
                return ResourceManager.GetString("STR_Cmd_ConvertLeadingSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert Leading Tabs to Spaces.
        /// </summary>
        public static string STR_Cmd_ConvertLeadingTabsToSpaces {
            get {
                return ResourceManager.GetString("STR_Cmd_ConvertLeadingTabsToSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert Spaces to Tabs.
        /// </summary>
        public static string STR_CMD_ConvertSpacesToTabs {
            get {
                return ResourceManager.GetString("STR_CMD_ConvertSpacesToTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert Tabs to Spaces.
        /// </summary>
        public static string STR_CMD_ConvertTabsToSpaces {
            get {
                return ResourceManager.GetString("STR_CMD_ConvertTabsToSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert text to upper case.
        /// </summary>
        public static string STR_Cmd_ConvertTextToUpperCase {
            get {
                return ResourceManager.GetString("STR_Cmd_ConvertTextToUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand text foldings.
        /// </summary>
        public static string STR_Cmd_ExpandTextFoldings {
            get {
                return ResourceManager.GetString("STR_Cmd_ExpandTextFoldings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Leading White Spaces.
        /// </summary>
        public static string STR_CMD_RemoveLeadingWhiteSpace {
            get {
                return ResourceManager.GetString("STR_CMD_RemoveLeadingWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Trailing White Space.
        /// </summary>
        public static string STR_CMD_RemoveTrailingWhiteSpace {
            get {
                return ResourceManager.GetString("STR_CMD_RemoveTrailingWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string STR_CmdName_Close {
            get {
                return ResourceManager.GetString("STR_CmdName_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string STR_CmdName_Copy {
            get {
                return ResourceManager.GetString("STR_CmdName_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selected item.
        /// </summary>
        public static string STR_CmdName_Copy_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Copy_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string STR_CmdName_Cut {
            get {
                return ResourceManager.GetString("STR_CmdName_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut selected item.
        /// </summary>
        public static string STR_CmdName_Cut_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Cut_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string STR_CmdName_Delete {
            get {
                return ResourceManager.GetString("STR_CmdName_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected item.
        /// </summary>
        public static string STR_CmdName_Delete_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Delete_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Line.
        /// </summary>
        public static string STR_CmdName_DeleteLine {
            get {
                return ResourceManager.GetString("STR_CmdName_DeleteLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes the current line of text.
        /// </summary>
        public static string STR_CmdName_DeleteLine_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_DeleteLine_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string STR_CmdName_Edit {
            get {
                return ResourceManager.GetString("STR_CmdName_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string STR_CmdName_Exit {
            get {
                return ResourceManager.GetString("STR_CmdName_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string STR_CmdName_Export {
            get {
                return ResourceManager.GetString("STR_CmdName_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert data into a file format that is suitable to other applications..
        /// </summary>
        public static string STR_CmdName_Export_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Export_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string STR_CmdName_File {
            get {
                return ResourceManager.GetString("STR_CmdName_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer Tool Window.
        /// </summary>
        public static string STR_CmdName_FileExplorer_TW {
            get {
                return ResourceManager.GetString("STR_CmdName_FileExplorer_TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string STR_CmdName_Find {
            get {
                return ResourceManager.GetString("STR_CmdName_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to line....
        /// </summary>
        public static string STR_CmdName_GotoLine {
            get {
                return ResourceManager.GetString("STR_CmdName_GotoLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string STR_CmdName_Help {
            get {
                return ResourceManager.GetString("STR_CmdName_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string STR_CmdName_Help_About {
            get {
                return ResourceManager.GetString("STR_CmdName_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log4Net Message Tool Window.
        /// </summary>
        public static string STR_CmdName_Log4Net_Message_TW {
            get {
                return ResourceManager.GetString("STR_CmdName_Log4Net_Message_TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log4Net Tool Window.
        /// </summary>
        public static string STR_CmdName_Log4Net_TW {
            get {
                return ResourceManager.GetString("STR_CmdName_Log4Net_TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string STR_CmdName_New {
            get {
                return ResourceManager.GetString("STR_CmdName_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Document.
        /// </summary>
        public static string STR_CmdName_New_Text {
            get {
                return ResourceManager.GetString("STR_CmdName_New_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a text file.
        /// </summary>
        public static string STR_CmdName_New_Text_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_New_Text_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UML Document.
        /// </summary>
        public static string STR_CmdName_New_UML {
            get {
                return ResourceManager.GetString("STR_CmdName_New_UML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a uml file.
        /// </summary>
        public static string STR_CmdName_New_UML_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_New_UML_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string STR_CmdName_Open {
            get {
                return ResourceManager.GetString("STR_CmdName_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log4Net Document.
        /// </summary>
        public static string STR_CmdName_Open_Log4Net {
            get {
                return ResourceManager.GetString("STR_CmdName_Open_Log4Net", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a Log4Net file.
        /// </summary>
        public static string STR_CmdName_Open_Log4Net_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Open_Log4Net_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Document.
        /// </summary>
        public static string STR_CmdName_Open_Text {
            get {
                return ResourceManager.GetString("STR_CmdName_Open_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a text file.
        /// </summary>
        public static string STR_CmdName_Open_Text_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Open_Text_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UML Document.
        /// </summary>
        public static string STR_CmdName_Open_UML {
            get {
                return ResourceManager.GetString("STR_CmdName_Open_UML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open an UML file.
        /// </summary>
        public static string STR_CmdName_Open_UML_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Open_UML_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string STR_CmdName_Paste {
            get {
                return ResourceManager.GetString("STR_CmdName_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste item from Windows clipboard.
        /// </summary>
        public static string STR_CmdName_Paste_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Paste_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties Tool Window.
        /// </summary>
        public static string STR_CmdName_Properties_TW {
            get {
                return ResourceManager.GetString("STR_CmdName_Properties_TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Documents.
        /// </summary>
        public static string STR_CmdName_RecentFiles {
            get {
                return ResourceManager.GetString("STR_CmdName_RecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Files Tool Window.
        /// </summary>
        public static string STR_CmdName_RecentFiles_TW {
            get {
                return ResourceManager.GetString("STR_CmdName_RecentFiles_TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string STR_CmdName_Redo {
            get {
                return ResourceManager.GetString("STR_CmdName_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo last undo.
        /// </summary>
        public static string STR_CmdName_Redo_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Redo_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string STR_CmdName_Replace {
            get {
                return ResourceManager.GetString("STR_CmdName_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string STR_CmdName_Save {
            get {
                return ResourceManager.GetString("STR_CmdName_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current file.
        /// </summary>
        public static string STR_CmdName_Save_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Save_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As ....
        /// </summary>
        public static string STR_CmdName_SaveAs {
            get {
                return ResourceManager.GetString("STR_CmdName_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file as certain type and in certain location.
        /// </summary>
        public static string STR_CmdName_SaveAs_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_SaveAs_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string STR_CmdName_SelectAll {
            get {
                return ResourceManager.GetString("STR_CmdName_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all items.
        /// </summary>
        public static string STR_CmdName_SelectAll_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_SelectAll_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings....
        /// </summary>
        public static string STR_CmdName_Settings {
            get {
                return ResourceManager.GetString("STR_CmdName_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Themes.
        /// </summary>
        public static string STR_CmdName_Themes {
            get {
                return ResourceManager.GetString("STR_CmdName_Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tools.
        /// </summary>
        public static string STR_CmdName_Tools {
            get {
                return ResourceManager.GetString("STR_CmdName_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string STR_CmdName_Undo {
            get {
                return ResourceManager.GetString("STR_CmdName_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo last edit.
        /// </summary>
        public static string STR_CmdName_Undo_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Undo_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string STR_CmdName_View {
            get {
                return ResourceManager.GetString("STR_CmdName_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize Workspace.
        /// </summary>
        public static string STR_CmdName_View_OptimizedWorkSpace {
            get {
                return ResourceManager.GetString("STR_CmdName_View_OptimizedWorkSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Page.
        /// </summary>
        public static string STR_CmdName_View_Start_Page {
            get {
                return ResourceManager.GetString("STR_CmdName_View_Start_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors.
        /// </summary>
        public static string STR_Contributors_Label {
            get {
                return ResourceManager.GetString("STR_Contributors_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your input is not sufficient. Correct the following problems or click Cancel..
        /// </summary>
        public static string STR_DIALOG_INPUT_PROBLEM_CAPTION {
            get {
                return ResourceManager.GetString("STR_DIALOG_INPUT_PROBLEM_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INS.
        /// </summary>
        public static string STR_EDIT_MODE_INSERT {
            get {
                return ResourceManager.GetString("STR_EDIT_MODE_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVR.
        /// </summary>
        public static string STR_EDIT_MODE_TYPEOVER {
            get {
                return ResourceManager.GetString("STR_EDIT_MODE_TYPEOVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading file.
        /// </summary>
        public static string STR_ERROR_LOADING_FILE_CAPTION {
            get {
                return ResourceManager.GetString("STR_ERROR_LOADING_FILE_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file:
        ///&apos;{0}&apos;
        ///
        ///does not exist or cannot be loaded.
        ///Do you want to remove this file from the list of recent files?.
        /// </summary>
        public static string STR_ERROR_LOADING_FILE_MSG {
            get {
                return ResourceManager.GetString("STR_ERROR_LOADING_FILE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML Files (*.html, *.htm)|*.html;*.htm|
        ///All Files (*.*)|*.*.
        /// </summary>
        public static string STR_ExportHTMLFileFilter {
            get {
                return ResourceManager.GetString("STR_ExportHTMLFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        public static string STR_FILE_DEFAULTNAME {
            get {
                return ResourceManager.GetString("STR_FILE_DEFAULTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error finding file.
        /// </summary>
        public static string STR_FILE_FINDING_CAPTION {
            get {
                return ResourceManager.GetString("STR_FILE_FINDING_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred.
        /// </summary>
        public static string STR_FILE_OPEN_ERROR_MSG_CAPTION {
            get {
                return ResourceManager.GetString("STR_FILE_OPEN_ERROR_MSG_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file cannot be edited because you do not have write access.
        ///Change the file access permissions or save the file in a different location if you want to edit it..
        /// </summary>
        public static string STR_FILE_READONLY_REASON_NO_WRITE_PERMISSION {
            get {
                return ResourceManager.GetString("STR_FILE_READONLY_REASON_NO_WRITE_PERMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file cannot be edited because another process is currently writing to it.
        ///End the other process and re-open the file or save the file in a different location if you want to edit it..
        /// </summary>
        public static string STR_FILE_READONLY_REASON_USED_BY_OTHER_PROCESS {
            get {
                return ResourceManager.GetString("STR_FILE_READONLY_REASON_USED_BY_OTHER_PROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string STR_FILESTATES_FileName {
            get {
                return ResourceManager.GetString("STR_FILESTATES_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path.
        /// </summary>
        public static string STR_FILESTATES_FilePath {
            get {
                return ResourceManager.GetString("STR_FILESTATES_FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size.
        /// </summary>
        public static string STR_FILESTATES_FileSize {
            get {
                return ResourceManager.GetString("STR_FILESTATES_FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time of last modification..
        /// </summary>
        public static string STR_FILESTATES_LASTMODIFICATION {
            get {
                return ResourceManager.GetString("STR_FILESTATES_LASTMODIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files (*.*)|*.*.
        /// </summary>
        public static string STR_FileType_FileFilter_AllFiles {
            get {
                return ResourceManager.GetString("STR_FileType_FileFilter_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# Files (*.cs)|*.cs.
        /// </summary>
        public static string STR_FileType_FileFilter_CSharp {
            get {
                return ResourceManager.GetString("STR_FileType_FileFilter_CSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML Files (*.htm,*.html,*.css,*.js)|*.htm;*.html;*.css;*.js.
        /// </summary>
        public static string STR_FileType_FileFilter_HTML {
            get {
                return ResourceManager.GetString("STR_FileType_FileFilter_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;log4net XML output (*.log4j,*.xml)|*.log4j;*.xml|All Files (*.*)|*.*&quot;.
        /// </summary>
        public static string STR_FileType_FileFilter_Log4j {
            get {
                return ResourceManager.GetString("STR_FileType_FileFilter_Log4j", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log4net XML output (*.log4j,*.log,*.txt,*.xml)|*.log4j;*.log;*.txt;*.xml.
        /// </summary>
        public static string STR_FileType_FileFilter_Log4NetPlusText {
            get {
                return ResourceManager.GetString("STR_FileType_FileFilter_Log4NetPlusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structured Query Language (*.sql) |*.sql.
        /// </summary>
        public static string STR_FileType_FileFilter_SQL {
            get {
                return ResourceManager.GetString("STR_FileType_FileFilter_SQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Files (*.txt)|*.txt.
        /// </summary>
        public static string STR_FileType_FileFilter_TextFiles {
            get {
                return ResourceManager.GetString("STR_FileType_FileFilter_TextFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unified Modeling Language (*.uml,*.xml)|*.uml;*.xml|All Files (*.*)|*.*&quot;.
        /// </summary>
        public static string STR_FileType_FileFilter_UML {
            get {
                return ResourceManager.GetString("STR_FileType_FileFilter_UML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string STR_FIND_BUTTON_CAPTION {
            get {
                return ResourceManager.GetString("STR_FIND_BUTTON_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and Replace....
        /// </summary>
        public static string STR_FIND_REPLACE_CAPTION {
            get {
                return ResourceManager.GetString("STR_FIND_REPLACE_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to replace all occurrences of &apos;{0}&apos; with &apos;{1}&apos;?.
        /// </summary>
        public static string STR_FINDREPLACE_ASK_REALLY_REPLACEEVERYTHING {
            get {
                return ResourceManager.GetString("STR_FINDREPLACE_ASK_REALLY_REPLACEEVERYTHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Sensitive.
        /// </summary>
        public static string STR_FINDREPLACE_CaseSensitive {
            get {
                return ResourceManager.GetString("STR_FINDREPLACE_CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Document.
        /// </summary>
        public static string STR_FINDREPLACE_CURRENTDOC {
            get {
                return ResourceManager.GetString("STR_FINDREPLACE_CURRENTDOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to Find:.
        /// </summary>
        public static string STR_FINDREPLACE_FINDLABEL {
            get {
                return ResourceManager.GetString("STR_FINDREPLACE_FINDLABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find _Next.
        /// </summary>
        public static string STR_FINDREPLACE_FINDNEXT {
            get {
                return ResourceManager.GetString("STR_FINDREPLACE_FINDNEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match whole Word.
        /// </summary>
        public static string STR_FINDREPLACE_MatchWholeWord {
            get {
                return ResourceManager.GetString("STR_FINDREPLACE_MatchWholeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Open Documents.
        /// </summary>
        public static string STR_FINDREPLACE_OPENDOCS {
            get {
                return ResourceManager.GetString("STR_FINDREPLACE_OPENDOCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string STR_FINDREPLACE_Options {
            get {
                return ResourceManager.GetString("STR_FINDREPLACE_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Expression.
        /// </summary>
        public static string STR_FINDREPLACE_RegularExpression {
            get {
                return ResourceManager.GetString("STR_FINDREPLACE_RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Replace.
        /// </summary>
        public static string STR_FINDREPLACE_Replace {
            get {
                return ResourceManager.GetString("STR_FINDREPLACE_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace _All.
        /// </summary>
        public static string STR_FINDREPLACE_ReplaceAll {
            get {
                return ResourceManager.GetString("STR_FINDREPLACE_ReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace all.
        /// </summary>
        public static string STR_FINDREPLACE_ReplaceAll_Caption {
            get {
                return ResourceManager.GetString("STR_FINDREPLACE_ReplaceAll_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with:.
        /// </summary>
        public static string STR_FINDREPLACE_ReplaceWith {
            get {
                return ResourceManager.GetString("STR_FINDREPLACE_ReplaceWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search up.
        /// </summary>
        public static string STR_FINDREPLACE_SearchBackWard {
            get {
                return ResourceManager.GetString("STR_FINDREPLACE_SearchBackWard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in:.
        /// </summary>
        public static string STR_FINDREPLACE_SearchInLABEL {
            get {
                return ResourceManager.GetString("STR_FINDREPLACE_SearchInLABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wildcards.
        /// </summary>
        public static string STR_FINDREPLACE_Wildcards {
            get {
                return ResourceManager.GetString("STR_FINDREPLACE_Wildcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Line ....
        /// </summary>
        public static string STR_GOTO_LINE_CAPTION {
            get {
                return ResourceManager.GetString("STR_GOTO_LINE_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        public static string STR_GOTOLINE_CANCEL_BUTTON {
            get {
                return ResourceManager.GetString("STR_GOTOLINE_CANCEL_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string STR_GOTOLINE_LINE_RANGE_LABEL {
            get {
                return ResourceManager.GetString("STR_GOTOLINE_LINE_RANGE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _OK.
        /// </summary>
        public static string STR_GOTOLINE_OK_BUTTON {
            get {
                return ResourceManager.GetString("STR_GOTOLINE_OK_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert or overtype text mode (switch on/of with insert key).
        /// </summary>
        public static string STR_Insert_Overtype_Mode_TT {
            get {
                return ResourceManager.GetString("STR_Insert_Overtype_Mode_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Case.
        /// </summary>
        public static string STR_Label_TextCase {
            get {
                return ResourceManager.GetString("STR_Label_TextCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White Spaces.
        /// </summary>
        public static string STR_Label_WhiteSpaces {
            get {
                return ResourceManager.GetString("STR_Label_WhiteSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta t:.
        /// </summary>
        public static string STR_LOG4NET_DELTATIME {
            get {
                return ResourceManager.GetString("STR_LOG4NET_DELTATIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A log4net document can be used to view the XML output from a log4net logger session..
        /// </summary>
        public static string STR_LOG4NET_DOCUMENTTAB_TT {
            get {
                return ResourceManager.GetString("STR_LOG4NET_DOCUMENTTAB_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a log item Id to scroll the document view to its item..
        /// </summary>
        public static string STR_LOG4NET_ENTERLOGID_TT {
            get {
                return ResourceManager.GetString("STR_LOG4NET_ENTERLOGID_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL.
        /// </summary>
        public static string STR_LOG4NET_FILTER_ALL {
            get {
                return ResourceManager.GetString("STR_LOG4NET_FILTER_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBUG.
        /// </summary>
        public static string STR_LOG4NET_FILTER_DEBUG {
            get {
                return ResourceManager.GetString("STR_LOG4NET_FILTER_DEBUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string STR_LOG4NET_FILTER_DEBUG_TT {
            get {
                return ResourceManager.GetString("STR_LOG4NET_FILTER_DEBUG_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        public static string STR_LOG4NET_FILTER_ERROR {
            get {
                return ResourceManager.GetString("STR_LOG4NET_FILTER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string STR_LOG4NET_FILTER_ERROR_TT {
            get {
                return ResourceManager.GetString("STR_LOG4NET_FILTER_ERROR_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FATAL.
        /// </summary>
        public static string STR_LOG4NET_FILTER_FATAL {
            get {
                return ResourceManager.GetString("STR_LOG4NET_FILTER_FATAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error.
        /// </summary>
        public static string STR_LOG4NET_FILTER_FATAL_TT {
            get {
                return ResourceManager.GetString("STR_LOG4NET_FILTER_FATAL_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO.
        /// </summary>
        public static string STR_LOG4NET_FILTER_INFO {
            get {
                return ResourceManager.GetString("STR_LOG4NET_FILTER_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string STR_LOG4NET_FILTER_INFO_TT {
            get {
                return ResourceManager.GetString("STR_LOG4NET_FILTER_INFO_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a filter criteria and activate the filter to customize the display..
        /// </summary>
        public static string STR_LOG4NET_FILTER_TOOLTIP {
            get {
                return ResourceManager.GetString("STR_LOG4NET_FILTER_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARN.
        /// </summary>
        public static string STR_LOG4NET_FILTER_WARN {
            get {
                return ResourceManager.GetString("STR_LOG4NET_FILTER_WARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string STR_LOG4NET_FILTER_WARN_TT {
            get {
                return ResourceManager.GetString("STR_LOG4NET_FILTER_WARN_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of actually displayed items (after applying filters)..
        /// </summary>
        public static string STR_LOG4NET_FILTERRESULT_TT {
            get {
                return ResourceManager.GetString("STR_LOG4NET_FILTERRESULT_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Log4net document cannot be edit. This is a read-only viewer document..
        /// </summary>
        public static string STR_LOG4NET_READONY_REASON {
            get {
                return ResourceManager.GetString("STR_LOG4NET_READONY_REASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Path to Clipboard.
        /// </summary>
        public static string STR_MRU_MENUITEM_COPYURL {
            get {
                return ResourceManager.GetString("STR_MRU_MENUITEM_COPYURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in containing Folder.
        /// </summary>
        public static string STR_MRU_MENUITEM_OpenInContainingFolder {
            get {
                return ResourceManager.GetString("STR_MRU_MENUITEM_OpenInContainingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with Windows Application....
        /// </summary>
        public static string STR_MRU_MENUITEM_OpenWithWindowsApp {
            get {
                return ResourceManager.GetString("STR_MRU_MENUITEM_OpenWithWindowsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string STR_MRU_MENUITEM_Remove {
            get {
                return ResourceManager.GetString("STR_MRU_MENUITEM_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while accessing the plugin directory..
        /// </summary>
        public static string STR_MSG_ACCESS_PLuginDir {
            get {
                return ResourceManager.GetString("STR_MSG_ACCESS_PLuginDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading UML plug-in.
        /// </summary>
        public static string STR_MSG_ACCESS_PLuginDir_Caption {
            get {
                return ResourceManager.GetString("STR_MSG_ACCESS_PLuginDir_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin directory created; no plugins loaded..
        /// </summary>
        public static string STR_MSG_DIRCREATED_NO_PLuginLoaded {
            get {
                return ResourceManager.GetString("STR_MSG_DIRCREATED_NO_PLuginLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin directory was not found..
        /// </summary>
        public static string STR_MSG_DIRCREATED_NO_PLuginLoaded_Caption {
            get {
                return ResourceManager.GetString("STR_MSG_DIRCREATED_NO_PLuginLoaded_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while initializing a plugin found in assembly &apos;{0}&apos;..
        /// </summary>
        public static string STR_MSG_ErrorLoadingPlugin {
            get {
                return ResourceManager.GetString("STR_MSG_ErrorLoadingPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error registering highlighting: &apos;{0}&apos;.
        /// </summary>
        public static string STR_MSG_ErrorRegisteringHighlighting {
            get {
                return ResourceManager.GetString("STR_MSG_ErrorRegisteringHighlighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected problem has occurred while saving the file..
        /// </summary>
        public static string STR_MSG_ErrorSavingFile {
            get {
                return ResourceManager.GetString("STR_MSG_ErrorSavingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading plugin assembly &apos;{0}&apos;..
        /// </summary>
        public static string STR_MSG_ErrorWhileLoadingPlugin {
            get {
                return ResourceManager.GetString("STR_MSG_ErrorWhileLoadingPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error &apos;{0}&apos;
        ///has occurred while saving a file..
        /// </summary>
        public static string STR_MSG_ErrorWhileSavingAFile {
            get {
                return ResourceManager.GetString("STR_MSG_ErrorWhileSavingAFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error &apos;{0}&apos;
        ///has occurred while saving the file:
        ///&apos;{1}&apos;.
        /// </summary>
        public static string STR_MSG_ErrorWhileSavingFileX {
            get {
                return ResourceManager.GetString("STR_MSG_ErrorWhileSavingFileX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string STR_MSG_FIND_Caption {
            get {
                return ResourceManager.GetString("STR_MSG_FIND_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no more search results to display..
        /// </summary>
        public static string STR_MSG_FIND_NO_MORE_ITEMS_FOUND {
            get {
                return ResourceManager.GetString("STR_MSG_FIND_NO_MORE_ITEMS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No further occurrence found..
        /// </summary>
        public static string STR_MSG_FIND_NO_MORE_ITEMS_FOUND2 {
            get {
                return ResourceManager.GetString("STR_MSG_FIND_NO_MORE_ITEMS_FOUND2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred..
        /// </summary>
        public static string STR_MSG_FIND_UNEXPECTED_ERROR {
            get {
                return ResourceManager.GetString("STR_MSG_FIND_UNEXPECTED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click on the link below to check if this is a known problem.
        ///
        ///Please report this problem if it is not known, yet.
        ///
        ///The problem report should contain the error message below (you can use the copy button)
        ///and a statement about the function/workflow you were using. Attach screenshots or sample files if applicable..
        /// </summary>
        public static string STR_MSG_IssueTrackerText {
            get {
                return ResourceManager.GetString("STR_MSG_IssueTrackerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Error.
        /// </summary>
        public static string STR_MSG_IssueTrackerTitle {
            get {
                return ResourceManager.GetString("STR_MSG_IssueTrackerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin not loaded..
        /// </summary>
        public static string STR_MSG_PluginNotLoaded {
            get {
                return ResourceManager.GetString("STR_MSG_PluginNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes for file &apos;{0}&apos;?.
        /// </summary>
        public static string STR_MSG_SaveChangesForFile {
            get {
                return ResourceManager.GetString("STR_MSG_SaveChangesForFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A plugin with the specified name has already been loaded..
        /// </summary>
        public static string STR_MSG_UML_PLugin_Duplicate {
            get {
                return ResourceManager.GetString("STR_MSG_UML_PLugin_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all MiniUml plugins loaded OK..
        /// </summary>
        public static string STR_MSG_UML_PLugin_NOTALL_Loaded {
            get {
                return ResourceManager.GetString("STR_MSG_UML_PLugin_NOTALL_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading UML plug-ins.
        /// </summary>
        public static string STR_MSG_UML_PLugin_NOTALL_Loaded_Caption {
            get {
                return ResourceManager.GetString("STR_MSG_UML_PLugin_NOTALL_Loaded_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error.
        /// </summary>
        public static string STR_MSG_Unexpected_Error {
            get {
                return ResourceManager.GetString("STR_MSG_Unexpected_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown document type.
        /// </summary>
        public static string STR_MSG_UnknownDocumentType {
            get {
                return ResourceManager.GetString("STR_MSG_UnknownDocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred..
        /// </summary>
        public static string STR_Msg_UnknownError {
            get {
                return ResourceManager.GetString("STR_Msg_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Error.
        /// </summary>
        public static string STR_MSG_UnknownError_Caption {
            get {
                return ResourceManager.GetString("STR_MSG_UnknownError_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while dispatching unhandled exception.
        /// </summary>
        public static string STR_MSG_UnknownError_InErrorDispatcher {
            get {
                return ResourceManager.GetString("STR_MSG_UnknownError_InErrorDispatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in shut-down process..
        /// </summary>
        public static string STR_MSG_UnknownError_InShutDownProcess {
            get {
                return ResourceManager.GetString("STR_MSG_UnknownError_InShutDownProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Behaviour.
        /// </summary>
        public static string STR_ProgramSettings_ApplicationBehaviour_Header {
            get {
                return ResourceManager.GetString("STR_ProgramSettings_ApplicationBehaviour_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progam Settings....
        /// </summary>
        public static string STR_ProgramSettings_Caption {
            get {
                return ResourceManager.GetString("STR_ProgramSettings_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string STR_REPLACE_BUTTON_CAPTION {
            get {
                return ResourceManager.GetString("STR_REPLACE_BUTTON_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to percent.
        /// </summary>
        public static string STR_SCALE_VIEW_PERCENT {
            get {
                return ResourceManager.GetString("STR_SCALE_VIEW_PERCENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string STR_SCALE_VIEW_PERCENT_SHORT {
            get {
                return ResourceManager.GetString("STR_SCALE_VIEW_PERCENT_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to font size.
        /// </summary>
        public static string STR_SCALE_VIEW_POINT {
            get {
                return ResourceManager.GetString("STR_SCALE_VIEW_POINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pt.
        /// </summary>
        public static string STR_SCALE_VIEW_POINT_SHORT {
            get {
                return ResourceManager.GetString("STR_SCALE_VIEW_POINT_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string STR_Settings_ApplicationLanguage {
            get {
                return ResourceManager.GetString("STR_Settings_ApplicationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the application to see the effect of this setting..
        /// </summary>
        public static string STR_Settings_ApplicationLanguage_TT {
            get {
                return ResourceManager.GetString("STR_Settings_ApplicationLanguage_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll below document.
        /// </summary>
        public static string STR_Settings_Editor_AllowScrollBelowDocument {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_AllowScrollBelowDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        public static string STR_Settings_Editor_CharacterSizeInPercent {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_CharacterSizeInPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string STR_Settings_Editor_CharacterSizeInPoints {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_CharacterSizeInPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust text editor character size.
        /// </summary>
        public static string STR_Settings_Editor_CharacterSizeSectionLabel {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_CharacterSizeSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Ruler.
        /// </summary>
        public static string STR_Settings_Editor_ColumnRulerSectionLabel {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_ColumnRulerSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert tabulator character into space character.
        /// </summary>
        public static string STR_Settings_Editor_ConvertTabToSpace {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_ConvertTabToSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut and copy current line of text.
        /// </summary>
        public static string STR_Settings_Editor_CutCopyWholeLine {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_CutCopyWholeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Email hyperlinks.
        /// </summary>
        public static string STR_Settings_Editor_EnableEmailHyperlinks {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_EnableEmailHyperlinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show file hyperlinks.
        /// </summary>
        public static string STR_Settings_Editor_EnableFileHyperlinks {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_EnableFileHyperlinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IME Support.
        /// </summary>
        public static string STR_Settings_Editor_EnableImeSupport {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_EnableImeSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangular selection (ALT+Shift or ALT+Mouse selection).
        /// </summary>
        public static string STR_Settings_Editor_EnableRectangularSelection {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_EnableRectangularSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text drag &amp; drop.
        /// </summary>
        public static string STR_Settings_Editor_EnableTextDragDrop {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_EnableTextDragDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to virtual space.
        /// </summary>
        public static string STR_Settings_Editor_EnableVirtualSpace {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_EnableVirtualSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperlinks.
        /// </summary>
        public static string STR_Settings_Editor_Hyperlink_Section {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_Hyperlink_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherit word wrap indentation.
        /// </summary>
        public static string STR_Settings_Editor_InheritWordWrapIndentation {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_InheritWordWrapIndentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require Control key for hyperlink click.
        /// </summary>
        public static string STR_Settings_Editor_RequireControlModifierForHyperlinkClick {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_RequireControlModifierForHyperlinkClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Editor Options.
        /// </summary>
        public static string STR_Settings_Editor_Section_Label {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_Section_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show box for control characters.
        /// </summary>
        public static string STR_Settings_Editor_ShowBoxForControlChar {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_ShowBoxForControlChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show column ruler.
        /// </summary>
        public static string STR_Settings_Editor_ShowColumnRulerOption {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_ShowColumnRulerOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show end of line.
        /// </summary>
        public static string STR_Settings_Editor_ShowEndOfLine {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_ShowEndOfLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show WWW hyperlinks.
        /// </summary>
        public static string STR_Settings_Editor_ShowHyperlinks {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_ShowHyperlinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Spaces.
        /// </summary>
        public static string STR_Settings_Editor_ShowSpaces {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_ShowSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Tabs.
        /// </summary>
        public static string STR_Settings_Editor_ShowTabs {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_ShowTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Wrap Text.
        /// </summary>
        public static string STR_Settings_Editor_WordWrap {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_WordWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourites (not sorted).
        /// </summary>
        public static string STR_Settings_MRU_Pin_At_Current_Position {
            get {
                return ResourceManager.GetString("STR_Settings_MRU_Pin_At_Current_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin entries at the beginning of the list.
        /// </summary>
        public static string STR_Settings_MRU_Pin_At_StartOption {
            get {
                return ResourceManager.GetString("STR_Settings_MRU_Pin_At_StartOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Recent Files (MRU) mode.
        /// </summary>
        public static string STR_Settings_MRU_Section_Label {
            get {
                return ResourceManager.GetString("STR_Settings_MRU_Section_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore last user session when application starts.
        /// </summary>
        public static string STR_Settings_RestoreUserSession {
            get {
                return ResourceManager.GetString("STR_Settings_RestoreUserSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Edi only once.
        /// </summary>
        public static string STR_Settings_RunEdiOnlyOnce {
            get {
                return ResourceManager.GetString("STR_Settings_RunEdiOnlyOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate background color.
        /// </summary>
        public static string STR_Settings_Text2HTML_AlternatingBackground {
            get {
                return ResourceManager.GetString("STR_Settings_Text2HTML_AlternatingBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to HTML Export.
        /// </summary>
        public static string STR_Settings_Text2HTML_GroupHeader {
            get {
                return ResourceManager.GetString("STR_Settings_Text2HTML_GroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show line numbers.
        /// </summary>
        public static string STR_Settings_Text2HTML_ShowLineNumbers {
            get {
                return ResourceManager.GetString("STR_Settings_Text2HTML_ShowLineNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file....
        /// </summary>
        public static string STR_STARTPAGE_FILEOPEN_TT {
            get {
                return ResourceManager.GetString("STR_STARTPAGE_FILEOPEN_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Page.
        /// </summary>
        public static string STR_STARTPAGE_TITLE {
            get {
                return ResourceManager.GetString("STR_STARTPAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit the Internet home page of this application.
        /// </summary>
        public static string STR_STARTPAGE_VISITPROJECTHOMEPAGE_TT {
            get {
                return ResourceManager.GetString("STR_STARTPAGE_VISITPROJECTHOMEPAGE_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Edi. Review this page to get started with this editor application..
        /// </summary>
        public static string STR_STARTPAGE_WELCOME_TT {
            get {
                return ResourceManager.GetString("STR_STARTPAGE_WELCOME_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready..
        /// </summary>
        public static string STR_StatusBar_Ready {
            get {
                return ResourceManager.GetString("STR_StatusBar_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding of the text in the current document.
        /// </summary>
        public static string STR_StatusBar_Textencoding_TT {
            get {
                return ResourceManager.GetString("STR_StatusBar_Textencoding_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X:.
        /// </summary>
        public static string STR_StatusBar_X_Coord_Label {
            get {
                return ResourceManager.GetString("STR_StatusBar_X_Coord_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column of the cursor in the current document.
        /// </summary>
        public static string STR_StatusBar_X_Coord_Label_TT {
            get {
                return ResourceManager.GetString("STR_StatusBar_X_Coord_Label_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y:.
        /// </summary>
        public static string STR_StatusBar_Y_Coord_Label {
            get {
                return ResourceManager.GetString("STR_StatusBar_Y_Coord_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row of the cursor in the current document.
        /// </summary>
        public static string STR_StatusBar_Y_Coord_Label_TT {
            get {
                return ResourceManager.GetString("STR_StatusBar_Y_Coord_Label_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theming Error.
        /// </summary>
        public static string STR_THEMING_CAPTION {
            get {
                return ResourceManager.GetString("STR_THEMING_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find Path to:
        ///&apos;{0}&apos;
        ///
        ///Please make sure this module is accessible..
        /// </summary>
        public static string STR_THEMING_MSG_CANNOT_FIND_PATH {
            get {
                return ResourceManager.GetString("STR_THEMING_MSG_CANNOT_FIND_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a text highlighting pattern.
        /// </summary>
        public static string STR_ToggleEditorOptionCmd_HighlightingDefinition_TT {
            get {
                return ResourceManager.GetString("STR_ToggleEditorOptionCmd_HighlightingDefinition_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show End of Line.
        /// </summary>
        public static string STR_ToggleEditorOptionCmd_ShowEndOfLine {
            get {
                return ResourceManager.GetString("STR_ToggleEditorOptionCmd_ShowEndOfLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show end of line.
        /// </summary>
        public static string STR_ToggleEditorOptionCmd_ShowEndOfLine_TT {
            get {
                return ResourceManager.GetString("STR_ToggleEditorOptionCmd_ShowEndOfLine_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Line Numbers.
        /// </summary>
        public static string STR_ToggleEditorOptionCmd_ShowLineNumbers {
            get {
                return ResourceManager.GetString("STR_ToggleEditorOptionCmd_ShowLineNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show line numbers.
        /// </summary>
        public static string STR_ToggleEditorOptionCmd_ShowLineNumbers_TT {
            get {
                return ResourceManager.GetString("STR_ToggleEditorOptionCmd_ShowLineNumbers_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Spaces.
        /// </summary>
        public static string STR_ToggleEditorOptionCmd_ShowSpaces {
            get {
                return ResourceManager.GetString("STR_ToggleEditorOptionCmd_ShowSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show space characters.
        /// </summary>
        public static string STR_ToggleEditorOptionCmd_ShowSpaces_TT {
            get {
                return ResourceManager.GetString("STR_ToggleEditorOptionCmd_ShowSpaces_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Tabs.
        /// </summary>
        public static string STR_ToggleEditorOptionCmd_ShowTabs {
            get {
                return ResourceManager.GetString("STR_ToggleEditorOptionCmd_ShowTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tabulator characters.
        /// </summary>
        public static string STR_ToggleEditorOptionCmd_ShowTabs_TT {
            get {
                return ResourceManager.GetString("STR_ToggleEditorOptionCmd_ShowTabs_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Wrap.
        /// </summary>
        public static string STR_ToggleEditorOptionCmd_WordWrap {
            get {
                return ResourceManager.GetString("STR_ToggleEditorOptionCmd_WordWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap text around document view.
        /// </summary>
        public static string STR_ToggleEditorOptionCmd_WordWrap_TT {
            get {
                return ResourceManager.GetString("STR_ToggleEditorOptionCmd_WordWrap_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Windows.
        /// </summary>
        public static string STR_VIEW_TOOLWINDOWS {
            get {
                return ResourceManager.GetString("STR_VIEW_TOOLWINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string STR_YALVLIb_Columns_MenuLabel {
            get {
                return ResourceManager.GetString("STR_YALVLIb_Columns_MenuLabel", resourceCulture);
            }
        }
    }
}
